#!/usr/bin/env python3

import sys 

from alarmeitbl.myeventloop import Timeout, Log
from alarmeitbl.comandos import *

def usage():
    print("Modo de usar: %s <ipaddr> <porta> <senha> <tam. senha> <comando> [param]" % sys.argv[0])
    print()
    print("Comandos disponíveis:", ", ".join(tratadores.keys()))
    print()
    print("Os comandos ativar e desativar aceitam um parâmetro adicional")
    print("  partição 1 até 254, ou omitir para atuar em todas partições.")
    sys.exit(1)

def parse_config():

    cfgfile = configparser.ConfigParser()
    cfgfile.read(sys.argv[1])
    if 'receptorip' not in cfgfile:
        usage()
    cfg = cfgfile['receptorip']
    return cfg

tratadores = { 'desativar': DesativarCentral,
                'ativar': AtivarCentral,
                'desligarsirene': DesligarSirene,
                'cancelarzona': CancelarZona,
                'reativarzona': ReativarZona,
                'status': SolicitarStatus,
                'limpardisparo': LimparDisparo }

Log.set_level(Log.DEBUG)

if len(sys.argv) < 6:
    usage()
ipaddr = sys.argv[1].lower().strip()
if ipaddr == 'auto':
    print("Para este fim, a config. caddr deve conter um endereço IP explícito.")
    usage()
cport = int(sys.argv[2]) or 9009
senha = int(sys.argv[3])
tam_senha = int(sys.argv[4])

comando = sys.argv[5]
if comando not in tratadores:
    usage()

particao = None
if len(sys.argv) == 7:
    try:
        particao = int(sys.argv[6])
    except ValueError:
        particao = -1
    if particao < 1 or particao > 254:
        usage()

class Observer:
    def __init__(self):
        pass

    def resultado(self, status):
        if status:
            print("Resultado: erro")
            sys.exit(status)

observer = Observer()

tratador = tratadores[comando](observer, ipaddr, cport, senha, tam_senha, [particao])

ev = EventLoop()
ev.loop()
print("Resultado: sucesso")
