#!/usr/bin/env python3

import sys, configparser

from alarmeitbl.myeventloop import Timeout, Log
from alarmeitbl.tratador import *
from alarmeitbl.tratador_fotos import *

def usage():
    print("Modo de usar: %s <arquivo de configuração> <indice> <foto>" % sys.argv[0])
    sys.exit(1)

def parse_config():
    if len(sys.argv) < 4:
        usage()

    cfgfile = configparser.ConfigParser()
    cfgfile.read(sys.argv[1])
    if 'receptorip' not in cfgfile:
        usage()
    cfg = cfgfile['receptorip']
    return cfg

Log.set_level(Log.INFO)

config = parse_config()
ipaddr = ("" + config['caddr']).lower().strip()
if ipaddr == 'auto':
    print("Para este fim, a config. caddr deve conter um endereço IP explícito.")
    usage()
cport = int(config['cport'])
senha = int(config['senha'])
tam_senha = int(config['tamanho'])
indice = int(sys.argv[2])
nrfoto = int(sys.argv[3])

t = TratadorDeFotos('dlfoto', "auto", cport, senha, tam_senha)
t.enfileirar(ipaddr, indice, nrfoto)
t.imediato()

ev = EventLoop()
ev.loop()
