#!/bin/sh

# Gancho para mensagens urgentes (de disparo)
#
# O conteúdo da mensagem é passado como um parâmetro de
# linha de comando ($1).
#
# Modifique este script para que a mensagem seja repassada
# via e-mail, SMS, Telegram, PushOver, etc. Ou remova seu
# conteúdo para que ele não faça nada (o script precisa
# existir e ser executável, mesmo que não faça nada.)

echo "$1" >> gancho_msg.txt
