#!/usr/bin/env python3

import sys, os

from alarmeitbl.myeventloop import Timeout, Log
from alarmeitbl.tratador import *
from alarmeitbl.tratador_fotos import *

Log.set_level(Log.INFO)
Log.set_file("receptorip.log")

def watchdog(to_obj):
    Log.info("receptor em funcionamento")
    p = os.popen("./gancho_watchdog", 'w')
    p.close()
    to_obj.reset(3600)

Timeout.new("watchdog", 15, watchdog)

host = "0.0.0.0"
port = int(sys.argv[1]) or 9009  # Porta deste Receptor IP
cport = int(sys.argv[2]) or 9009 # Porta da central de alarme
senha = int(sys.argv[3])         # Senha de acesso remoto (usuário 98)
tam_senha = int(sys.argv[4])     # Tamanho da senha (4 ou 6 dígitos)

Tratador.tratador_de_fotos = TratadorDeFotos(cport, senha, tam_senha)

ev = TCPServerEventLoop((host, port), TCPListener, Tratador)

def central_nao_conectada(to_obj):
    centrais_conectadas = 0
    for h in Handler.items.values():
        if isinstance(h, Tratador):
            centrais_conectadas += 1
    if not centrais_conectadas:
        Log.info("nenhuma central conectada")
        p = os.popen("./gancho_central", 'w')
        p.close()
    to_obj.restart()

Timeout.new("central_nc", 3600, central_nao_conectada)

ev.loop()
