#!/usr/bin/env python3

import sys, os, configparser, re

from alarmeitbl.myeventloop import Timeout, Log
from alarmeitbl.tratador import *
from alarmeitbl.tratador_fotos import *

def usage():
    print("Modo de usar: %s <arquivo de configuração>" % sys.argv[0])
    sys.exit(1)

def parse_config():
    if len(sys.argv) < 2:
        usage()

    cfgfile = configparser.ConfigParser()
    cfgfile.read(sys.argv[1])
    if 'receptorip' not in cfgfile:
        usage()
    cfg = cfgfile['receptorip']
    return cfg

Log.set_level(Log.INFO)
Log.set_file("receptorip.log")

def watchdog(to_obj):
    Log.info("receptor em funcionamento")
    p = os.popen("./gancho_watchdog", 'w')
    p.close()
    to_obj.reset(3600)

Timeout.new("watchdog", 15, watchdog)

config = parse_config()
host = ("" + config['addr']).lower().strip()
port = int(config['port'])
caddr = ("" + config['caddr']).lower().strip()
cport = int(config['cport'])
senha = int(config['senha'])
tam_senha = int(config['tamanho'])
centrais = re.compile("" + config['centrais'])

Tratador.tratador_de_fotos = TratadorDeFotos('receptorip', caddr, cport, senha, tam_senha)

def valida_central(id_central):
    return centrais.match(id_central)

Tratador.valida_central = valida_central

ev = TCPServerEventLoop((host, port), TCPListener, Tratador)

def central_nao_conectada(to_obj):
    centrais_conectadas = 0
    for h in Handler.items.values():
        if isinstance(h, Tratador):
            centrais_conectadas += 1
    if not centrais_conectadas:
        Log.info("nenhuma central conectada")
        p = os.popen("./gancho_central", 'w')
        p.close()
    to_obj.restart()

Timeout.new("central_nc", 3600, central_nao_conectada)

ev.loop()
