#!/usr/bin/env python3

import sys, re

if len(sys.argv) < 3:
    print("Uso: %s <expressão regular> <id da central>" % sys.argv[0])
    sys.exit(1)

centrais = re.compile(sys.argv[1])
if centrais.match(sys.argv[2]):
    print("Deu match")
else:
    print("Não deu match")
